### ISSUE TITLE
Normalization in replay

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#110]
Using the image_and_scalar.py example, data cannot be normalized.  Order of operations:
1. Load a dataset
2. Bin on `img`
3. Normalize against `Tsam`
4. Check the box next to `img`
5. The following stack trace is produced:

```
Traceback (most recent call last):
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/enaml/qt/qt_abstract_button.py", line 76, in on_clicked
    self.declaration.clicked(checked)
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/enaml/core/expression_engine.py", line 210, in write
    pair.writer(owner, name, change)
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "/home/edill/dev/python/dataportal/dataportal/replay/muxer/view.enaml", line 16, in <module>
    muxer_model.normalize(column_model.name, checked)
  File "/home/edill/dev/python/dataportal/dataportal/replay/muxer/model.py", line 349, in normalize
    self.dataframe[col] *= self.dataframe[(self.norm_column, 'val')]
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/pandas/core/frame.py", line 1778, in __getitem__
    return self._getitem_multilevel(key)
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/pandas/core/frame.py", line 1822, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/home/edill/anaconda/envs/nikea2/lib/python2.7/site-packages/pandas/core/index.py", line 4141, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 134, in pandas.index.IndexEngine.get_loc (pandas/index.c:3807)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:3687)
  File "pandas/hashtable.pyx", line 696, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12310)
  File "pandas/hashtable.pyx", line 704, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12261)
KeyError: ('Tsam', 'val')
```

**Comment by ericdill** [comment]
Moved to NSLS-II/replay#13
