### ISSUE TITLE
Mpl/Pandas plotting bug!

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#32]
Error message is this: for commit https://github.com/ericdill/DataBroker/commit/0b5b74fd8cb023a459c834368373e47fd1cb4838

```
Traceback (most recent call last):
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 338, in resizeEvent
    self.draw()
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 148, in draw
    FigureCanvasAgg.draw(self)
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/figure.py", line 1011, in draw
    self.tight_layout(renderer, **self._tight_parameters)
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/figure.py", line 1654, in tight_layout
    rect=rect)
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 352, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 131, in auto_adjust_subplotpars
    fig.transFigure.inverted())
  File "/home/edill/anaconda/envs/nikea/lib/python2.7/site-packages/matplotlib/transforms.py", line 1057, in __init__
    assert bbox.is_bbox
AttributeError: 'NoneType' object has no attribute 'is_bbox
```

**Comment by ericdill** [comment]
@tacaswell @danielballan any ideas?  PS simple scalar plotting now works in replay :)

**Comment by tacaswell** [comment]
tight layout can be finicky as thing have to be drawn at least once before their sizes are known (for example text) but this looks like it is failing to build the inverse transform for the figure units -> screen units transformation.  I suspect that there is a race-condition going on between the tight_layout black magic and the enaml black magic.

**Comment by danielballan** [comment]
Nice to hear that scalar plotting works. I avoid using pandas plotting methods in a package. (And, yes, Tom avoids them altogether.) They are convenient for quick inspection, but the defaults imposed by pandas add a new hidden layer of complexity. What happens if you build the subplots explicitly? And, following @tacaswell's line of thought, what happens with and without tight_layout? (Relevant docs are [here](http://matplotlib.org/users/tight_layout_guide.html).)

**Comment by ericdill** [comment]
Thanks for the responses guys.  @danielballan I'm not entirely sure how to use tight_layout with the plot() function on the dataframe object.  Also, just so it's clear, this mechanism of plotting was not going to be the major use-case of Replay, just perhaps a very nice convience function to display the data in all columns.

**Comment by ericdill** [comment]
Interesting... I can get it to draw with subplots by using figure.set_tight_layout(False).  It continues to throw the same error though if I call figure.tight_layout() after the dataframe.plot() function gets called.  

``` python
    def plot_by_time(self):
        df = self.data_muggler._dataframe
        nrows, ncols = self.get_rows_cols()
        subplots = not self.single_plot
        self._fig.set_tight_layout(False)
        df.plot(ax=self._ax, subplots=subplots, marker='o',
                layout=(nrows, ncols))
        self._fig.canvas.draw()
        self._fig.tight_layout()
```

**Comment by tacaswell** [comment]
sigh, something else fishy is going on here.

To make sure I understand correctly:
- pandas works fine without tight_layout
- using `df.plot` makes tight_layout stop working

Try always setting `subplots` to `False` to try and convince pandas to not screw with the existing axes?

I suspect what you really want from pandas is to steal their ticker logic, which is on my list of things to do anyway....

**Comment by goyodiaz** [comment]
`DataFrame.hist()` sometimes creates an invisible axes and `tight_layout()` is not prepared to deal with this. See https://github.com/pydata/pandas/issues/9351

@tacaswell can you confirm whether this is a matplotlib issue?
